#!/bin/zsh -f

_gcc_use='-d -go -gtk -objc -objc++ -objc-gc -graphite -lto'
echo "sys-devel/gcc $_gcc_use"

_binutils_use='-multislot -multitarget'
echo "sys-devel/binutils $_binutils_use"

_pkgconfig_use='internal-glib'
echo "dev-util/pkgconfig $_pkgconfig_use"

